Ke 12.8.23 unit mthds
KevinMonahanUWM/SchedulerApp pull request #48
Opened 2023-12-09 19:32 UTC by Kiran-Ee

These methods pass (getAllSecAsgmts + setSkills)

2023-12-09 23:44 UTC, KevinMonahanUWM commented on TAScheduler/models.py
> +    skills = models.CharField(max_length=30,default="idk why this is needed")
This should be a Django Textfield. That will take a large input of text and not have a maximum length

2023-12-09 23:46 UTC, KevinMonahanUWM commented on TAScheduler/UnitTests/tests.py
> +class AdminGetAllSecAsgmt(TestCase):  # Kiran
Should be TestAdminGetAllSectionAssignments. Need to have the word "Test" in order to run unittests

2023-12-09 23:46 UTC, KevinMonahanUWM requested changes
Please take a look at my comments

2023-12-10 22:44 UTC, JosiahDeYong approved these changes

2023-12-12 15:07 UTC, merged